inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
