language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
install:
  - bundle install --path vendor/bundle
  - cp -n config/database.yml.example config/database.yml
  - rake db:setup
script:
  - bundle exec rubocop
  - bundle exec rake spec
notifications:
  email: false
addons:
  code_climate:
    repo_token: ac919a1e07a87ee109b1911d4f593f99f7238d5f169f4c993b9a059e7cf42c46
after_script:
  - vendor/bin/test-reporter
